Repository adfinis/helm-charts, pull requests merged in 2021-09, with the labels that each got.

#326 feat(azure-apps): Add azure-apps for azure related components
  .github/workflows/pr-sizing.yaml
  README.md
  charts/azure-apps/.helmignore
  charts/azure-apps/Chart.lock
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/ci/default-values.yaml
  charts/azure-apps/examples/azure-kv-csi-provider.yaml
  charts/azure-apps/templates/NOTES.txt
  charts/azure-apps/templates/azure-kv-csi-provider.yaml
  charts/azure-apps/values.yaml
Labels: size/L

#328 feat(infra-apps): argocd chart bump to 3.17
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#348 feat(misc-apps): add chartmuseum deployment
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/ci/default-values.yaml
  charts/misc-apps/examples/chartmuseum.yaml
  charts/misc-apps/templates/chartmuseum.yaml
  charts/misc-apps/values.yaml
Labels: size/L

#349 fix(infra-apps): update kured to chart to 2.9.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#350 fix(infra-apps): valid kube-event-exporter chart version
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#351 chore(filebeat): update to 7.14.*
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/S

#352 fix(azure-apps): Change Azure chart name
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/XS

#353 chore(storage-apps): update cephfs & rbd
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/values.yaml
Labels: size/S

#354 chore(infra-apps): Update certMgr
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#357 feat(security-apps): gatekeeper 3.6.0
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#356 feat(caasperli): extra annotations for prometheus-operator CRDs
  charts/caasperli/Chart.yaml
  charts/caasperli/README.md
  charts/caasperli/templates/grafana/configmap-dashboard.yaml
  charts/caasperli/templates/prometheus/podmonitor.yaml
  charts/caasperli/templates/prometheus/servicemonitor.yaml
  charts/caasperli/values.yaml
Labels: size/S

#358 feat(infra-apps): update argocd-notifications to 1.5
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#360 feat(security-apps): upgrade dex Helm Chart to 0.6.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#361 feat(security-apps): upgrade secrets-store-csi-driver to 0.3.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#364 feat(infra-apps): upgrade kubePrometheusStack to 18.0.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#366 chore(misc-apps): metallb use official helm repo
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/examples/metallb.yaml
  charts/misc-apps/values.yaml
Labels: size/S

#367 chore(openshift-etcd-backup): bump to latest v1.4.1 appVersion
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/XS

#368 fix(timed): update workreport template
  charts/timed/Chart.yaml
  charts/timed/files/workreport.ots
Labels: size/XS

#370 fix(timed): remove duplicate label and cleanup docs
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/_helpers.tpl
  charts/timed/values.yaml
Labels: size/S

#371 fix(ci): replace pre-commit action with working script
  .github/workflows/test.yaml
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/examples/secrets-store-csi-driver-provider-azure.yaml
  charts/caasperli/Chart.yaml
  charts/caasperli/README.md
  hack/ci/github/setup/pre-commit.sh
  hack/sh/deps/pre-commit.sh
Labels: size/S

#372 chore(ci): update helm to 3.7.0
  .env
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: size/XS

#374 chore(sec-apps): use new vault 0.16.0 version
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#373 feat(misc-apps): Bump signalilo
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#376 fix(timed): update deprecated CronJob version
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/cronjob-backend.yaml
Labels: size/XS

#377 fix(azure-apps): change default namespace for vault
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/S

#380 fix(timed): use sync waves for db migrations
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/cronjob-backend.yaml
  charts/timed/templates/deployment-backend.yaml
  charts/timed/templates/deployment-frontend.yaml
  charts/timed/templates/job-dbmigrate.yaml
Labels: size/S

#383 feat(infra-apps): upgrade argocd to 3.22.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#385 fix(timed): add logo and update font in workreport
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/files/workreport.ots
Labels: size/XS
