Repository adfinis/helm-charts, pull requests merged in 2021-11, with the labels that each got.

#423 feat(timed): change column for total hours for tasks
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/files/workreport.ots
Labels: size/XS

#421 feat: cert-manager-monitoring chart
  README.md
  charts/cert-manager-monitoring/Chart.yaml
  charts/cert-manager-monitoring/README.md
  charts/cert-manager-monitoring/ci/default-values.yaml
  charts/cert-manager-monitoring/grafana/dashboards/cert-manager.json
  charts/cert-manager-monitoring/templates/NOTES.txt
  charts/cert-manager-monitoring/templates/_helpers.tpl
  charts/cert-manager-monitoring/templates/grafana/configmap-dashboard.yaml
  charts/cert-manager-monitoring/templates/prometheus/prometheusrule.yaml
  charts/cert-manager-monitoring/values.yaml
  hack/deploy/init.sh
Labels: size/XXL

#422 feat(infra-apps): add cert-manager-monitoring
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/templates/cert-manager-monitoring.yaml
  charts/infra-apps/values.yaml
Labels: size/M

#424 fix(cert-manager-monitoring): configurable job label for CertManagerAbsent
  charts/cert-manager-monitoring/Chart.yaml
  charts/cert-manager-monitoring/README.md
  charts/cert-manager-monitoring/templates/prometheus/prometheusrule.yaml
  charts/cert-manager-monitoring/values.yaml
Labels: size/S

#426 feat: hide deprecated charts from docs
  README.md
  hack/config/update-readme/README.md.gotmpl
Labels: size/XS

#428 chore: hints for linguist
  .gitattributes
Labels: size/S

#427 docs: initialise Argo CD app of apps documentation
  README.md
  docs/README.md
  docs/argocd-app-of-apps.md
  hack/config/update-readme/README.md.gotmpl
Labels: size/L

#429 fix(openshift-etcd-backup): app-version should be 1.5.2
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/XS

#375 Upgrade huawei-csi-plugin chart to v2.2.14
  charts/huawei-csi-plugin/Chart.yaml
  charts/huawei-csi-plugin/README.md
  charts/huawei-csi-plugin/docs/INSTALL.md
  charts/huawei-csi-plugin/templates/configmap.yaml
  charts/huawei-csi-plugin/templates/daemonset-node.yaml
  charts/huawei-csi-plugin/templates/deployment-controller.yaml
  charts/huawei-csi-plugin/templates/rbac.yaml
  charts/huawei-csi-plugin/templates/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
  charts/huawei-csi-plugin/templates/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
  charts/huawei-csi-plugin/templates/snapshot.storage.k8s.io_volumesnapshots.yaml
  charts/huawei-csi-plugin/values.yaml
  hack/chart-testing/ct-install.yaml
Labels: size/XL

#431 chore: mark sentry-apps as deprecated
  README.md
  charts/sentry-apps/Chart.yaml
  charts/sentry-apps/README.md
Labels: size/S

#432 fix(infra-apps): cleanup copy paste error in values
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#433 feat(infra-apps): rbac-manager chart 1.9.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#434 fix(huawei-csi-plugin): add runAUser to run huawei-csi-driver container as root
  charts/huawei-csi-plugin/Chart.yaml
  charts/huawei-csi-plugin/README.md
  charts/huawei-csi-plugin/values.yaml
Labels: size/XS

#438 feat(tracing-apps): bump jaeger-operator
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/S

#435 feat(infra-apps): bump kubernetes-event-exporter to 1.2.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#436 feat(misc-apps): chartmuseum 3.3.*
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#437 feat(security-apps): gatekeeper 3.7.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#439 fix(back8sup): use correct apiVersion and upgrade to lastest patch version
  charts/back8sup/Chart.yaml
  charts/back8sup/README.md
  charts/back8sup/templates/cronjob.yaml
Labels: size/XS

#441 feat(azure-apps): add promitor.io
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/ci/default-values.yaml
  charts/azure-apps/examples/promitor.yaml
  charts/azure-apps/templates/NOTES.txt
  charts/azure-apps/templates/promitor-resource-discovery.yaml
  charts/azure-apps/templates/promitor-scraper.yaml
  charts/azure-apps/values.yaml
Labels: size/L

#430 feat(timed): add DATA_UPLOAD_MAX_NUMBER_FIELDS to env
  README.md
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/configmap-backend.yaml
  charts/timed/values.yaml
Labels: size/S

#443 fix(azure-apps) promitor repoURL trailing slash
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/S

#444 feat(infra-apps): argocd-notifications 1.6
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#447 feat(infra-apps): kube-prometheus-stack 21.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S
