Repository adfinis/helm-charts, pull requests merged in 2021-12, with the labels that each got.

#445 feat(security-apps): Add dex-k8s-authenticator
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/examples/dex-k8s-authenticator.yaml
  charts/security-apps/templates/dex-k8s-authenticator.yaml
  charts/security-apps/values.yaml
Labels: size/L

#461 fix(CODEOWNERS): removes sinicis, adds @tongpu
  CODEOWNERS
Labels: size/XS

#459 feat(security-apps): falco-exporter 0.6
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#462 feat(misc-apps): metallb-0.11
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#460 feat(security-apps): vault-0.18
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#463 feat(infra-apps/velero): upgrade to 2.27
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#464 feat(infra-apps/argocd): upgrade to 3.27
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#465 feat(infra-apps/kubePrometheusStack): upgrade to 23.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#466 feat(infra/thanos): update to 8.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#469 feat(timed): add customer-center email
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/configmap-backend.yaml
  charts/timed/values.yaml
Labels: size/S

#471 fix(infra-apps): removove trailing whitespace in thanos example
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/examples/thanos.yaml
Labels: size/S

#472 docs: fix pre-commit command in pr template
  .github/pull_request_template.md
Labels: size/XS

#474 feat(infra-apps): argocd chart 3.28
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#470 chore(customer-center): update to v3.0.0
  README.md
  charts/customer-center/Chart.lock
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
  charts/customer-center/templates/NOTES.txt
  charts/customer-center/templates/configmap-backend.yaml
  charts/customer-center/templates/deployment-backend.yaml
  charts/customer-center/templates/deployment.yaml
  charts/customer-center/templates/ingress.yaml
  charts/customer-center/templates/secret-backend.yaml
  charts/customer-center/templates/service-backend.yaml
  charts/customer-center/templates/service.yaml
  charts/customer-center/values.yaml
Labels: size/L

#468 feat(misc-apps): update chartmuseum to 3.4.*
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#478 chore(*-apps): get rid of redundant version info
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/backup-apps/Chart.yaml
  charts/backup-apps/README.md
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
Labels: size/M

#479 feat(timed): add cors_allowed_origins env variable
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/configmap-backend.yaml
  charts/timed/values.yaml
Labels: size/XS

#477 docs(app-of-apps): argoconfigs template
  docs/argocd-app-of-apps.md
Labels: size/M

#480 chore(customer-center): update to v3.0.1
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#481 chore(customer-center): update customer-center to v3.0.2
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#482 chore(customer-center): update to v3.0.3
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#476 feat(argo-apps): add argo rollouts
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/ci/default-values.yaml
  charts/argo-apps/examples/argo-rollouts.yaml
  charts/argo-apps/templates/argo-rollouts.yaml
  charts/argo-apps/values.yaml
Labels: size/M

#484 chore(customer-center): update customer-center to v3.0.4
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
  charts/customer-center/templates/configmap-frontend.yaml
  charts/customer-center/values.yaml
Labels: size/S

#485 fix(customer-center): update metadata
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
  charts/customer-center/templates/configmap-frontend.yaml
Labels: size/XS

#486 fix(customer-center): read config map from deployment
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
  charts/customer-center/templates/configmap.yaml
  charts/customer-center/templates/deployment.yaml
  charts/customer-center/values.yaml
Labels: size/S

#489 chore(customer-center): update customer-center to v3.0.7
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#488 feat(storage-apps): remove nfs-client-provisioner
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/ci/default-values.yaml
  charts/storage-apps/examples/nfs-client-provisioner.yaml
  charts/storage-apps/templates/nfs-client-provisioner.yaml
  charts/storage-apps/values.yaml
Labels: size/M

#490 feat(azure-apps): bump promitor resource discovery
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/XS

#491 fix(hack): make helm-docs wrapper complain if template is missing
  .env
  hack/helm-docs.sh
Labels: size/XS

#493 timed update
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/XS

#492 chore(infra-apps): update argo-cd from 3.28.* to 3.29.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#495 chore(customer-center): update to v3.0.8
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#496 chore(customer-center): update to v3.0.9
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#497 feat(barman): bump to 2.17
  charts/barman/Chart.yaml
  charts/barman/README.md
  charts/barman/templates/deployment.yaml
  charts/barman/values.yaml
Labels: size/S

#498 chore(customer-center): update to v3.1.1
  README.md
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#501 customer center update
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#500 fix(timed): update certificate apiVersion
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/certificate-psql.yaml
Labels: size/XS

#502 fix(barman): fix entrypoint override by re-adding args
  charts/barman/Chart.yaml
  charts/barman/README.md
  charts/barman/templates/deployment.yaml
Labels: size/XS

#503 feat: kured 1.9.0 (chart version 2.11)
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#504 feat(azure-apps): promitor scraper 2.7
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/XS

#505 fix(timed): change total hours column in workreport
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/files/workreport.ots
Labels: size/XS

#506 chore(customer-center): update to v3.1.6
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#507 update cc
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS
