Repository adfinis/helm-charts, pull requests merged in 2021-08, with the labels that each got.

#314 feat(infra-apps): bump kube-prometheus-stack to 17.1.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#315 feat(security-apps): bump falco to 1.15.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#316 chore(Chart.yaml): bump to openshift-etcd-backup to latest v1.4.0
  README.md
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/XS

#317 drop duplicate key name
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/templates/cronjob.yaml
Labels: size/XS

#318 feat(security-apps): secrets-store-csi-drive 0.1.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/examples/secrets-store-csi-driver.yaml
  charts/security-apps/values.yaml
Labels: size/S

#319 Fix for openshift-etcd-backup cronjob
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/templates/cronjob.yaml
Labels: size/XS

#320 feat(timed): add image tag for backend
  README.md
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#321 feat(infra-apps): bump argocd chart to 3.12.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#323 feat(infra-apps): introduce kubernetes-event-exporter
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/ci/default-values.yaml
  charts/infra-apps/examples/kubernetes-event-exporter.yaml
  charts/infra-apps/templates/kubernetes-event-exporter.yaml
  charts/infra-apps/values.yaml
Labels: size/M

#324 chore(customer-center): update customer-center to v2.1.0
  README.md
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS
