Repository adfinis/helm-charts, pull requests merged in 2022-05, with the labels that each got.

#678 feat(storage-apps): add minio
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/ci/default-values.yaml
  charts/storage-apps/examples/minio.yaml
  charts/storage-apps/templates/minio.yaml
  charts/storage-apps/values.yaml
Labels: size/M

#677 feat(security-apps): Bump dex to 0.8
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#679 feat(tracing-apps): update opentelemetry-collector from 0.12 to 0.15
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/XS

#674 feat(infra-apps): Kube-prometheus-stack to 35.0.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#676 feat(logging-apps): Bump filebeat to 7.17
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/XS

#643 feat(infra-apps): allow adding annotations at the app level
  charts/infra-apps/Chart.lock
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/templates/argocd.yaml
  charts/infra-apps/templates/cert-manager-monitoring.yaml
  charts/infra-apps/templates/certmgr-issuers.yaml
  charts/infra-apps/templates/certmgr.yaml
  charts/infra-apps/templates/ingress.yaml
  charts/infra-apps/templates/kubernetes-event-exporter.yaml
  charts/infra-apps/templates/kured.yaml
  charts/infra-apps/templates/monitoring.yaml
  charts/infra-apps/templates/rbac.yaml
  charts/infra-apps/templates/thanos.yaml
  charts/infra-apps/templates/velero.yaml
  charts/infra-apps/values.yaml
Labels: size/L

#595 feat(security-apps): secrets-store-csi-driver 1.1.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#596 feat(azure-apps): csi-secrets-store-provider-azure 1.1.*
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/S

#675 feat(infra-apps): Bump thanos to 35.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#680 feat(argo-apps): upgrade rollouts from 2.12 to 2.14 + spring cleaning
  charts/argo-apps/Chart.lock
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/templates/argo-rollouts.yaml
  charts/argo-apps/templates/argocd-notifications.yaml
  charts/argo-apps/values.yaml
Labels: size/M

#681 chore(falco): update to 1.18.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#682 chore(customer-center): update to v3.2.3
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#610 feat(vault-monitoring): add VaultAutopilotNodeHealthy rule
  charts/vault-monitoring/Chart.yaml
  charts/vault-monitoring/README.md
  charts/vault-monitoring/values.yaml
Labels: size/S

#683 chore(sec-apps): update vaultMonitoring
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#684 chore(update): ceph-csi to 3.6.*
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/values.yaml
Labels: size/S

#686 fix(argoconfig): no defaults in appProject resources
  charts/argoconfig/Chart.yaml
  charts/argoconfig/README.md
  charts/argoconfig/templates/_appProject.yaml
Labels: size/S

#687 feat(infra-apps): update argo-cd chart from 4.5 to 4.6
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#688 feat(infra-apps): update kured from 2.13 to 2.14
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#689 feat(infra-apps): update thanos from 10.3 to 10.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#691 feat(barman): add optional annotations to PVCs
  charts/barman/Chart.yaml
  charts/barman/README.md
  charts/barman/templates/pvc.yaml
  charts/barman/values.yaml
Labels: size/S

#692 fix(mopsos): update mopsos from 0.3.3 to 0.3.4
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Labels: size/S

#693 feat(infra-apps): update argo-cd chart from 4.6 to 4.7
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#694 feat(security-apps): add neuvector core + monitor
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/ci/default-values.yaml
  charts/security-apps/examples/neuvector.yaml
  charts/security-apps/values.yaml
Labels: size/M

#695 fix(security-apps): remove trailing slash in neuvector chart repo
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#696 fix(security-apps): add actual neuvector apps
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/templates/neuvector.yaml
  charts/security-apps/templates/neuvectorMonitor.yaml
Labels: size/M

#697 docs: update helm-docs from 1.8.1 to 1.10.0
  .env
  .pre-commit-config.yaml
  charts/barman/Chart.yaml
  charts/barman/README.md
  charts/barman/values.yaml
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
  charts/osschallenge/Chart.yaml
  charts/osschallenge/README.md
  charts/rmd/Chart.yaml
  charts/rmd/README.md
  charts/timed/Chart.yaml
  charts/timed/README.md
Labels: size/M
