Repository adfinis/helm-charts, pull requests merged in 2022-06, with the labels that each got.

#698 chore(misc-apps): update chartmuseum to 3.8.*
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/XS

#699 chore(security-apps): gatekeeper update to 3.8.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#700 chore(backup-apps): update barman to 0.8.*
  charts/backup-apps/Chart.yaml
  charts/backup-apps/README.md
  charts/backup-apps/values.yaml
Labels: size/XS

#706 feat(infra-apps): update argo-cd from 4.8 to 4.9
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#723 chore(infra-apps): Update kube-prometheus-stack to v36.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#722 feat(falco): update to 1.19.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#724 feat(fluentD): update to 5.11.*
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/XS

#725 feat(infra-apps): update kured from 2.14 to 2.15
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#728 feat(logging-apps): update fluentbit from 0.19 to 0.20
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/XS

#727 chore(security-apps): Dex upgrade to v0.9
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#729 chore(infra-apps): Update thanos to v10.5
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#730 feat(tracing-apps): update opentelemetry-collector from 0.15.* to 0.20.1
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/XS

#731 feat(security-apps): update vault from 0.19.* to 0.20.1
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#732 fix(mopsos): update from 0.3.5 to 0.3.6
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Labels: size/S

#708 Some changes and modifications
  charts/barman/.helmignore
  charts/barman/Chart.yaml
  charts/barman/README.md
  charts/barman/examples/barman.yaml
  charts/barman/templates/configmap-barman-backups.yaml
  charts/barman/templates/configmap-barman-cron.yaml
  charts/barman/templates/configmap-barman.yaml
  charts/barman/templates/configmap-entrypoint.yaml
  charts/barman/templates/configmap.yaml
  charts/barman/templates/deployment.yaml
  charts/barman/values.yaml
Labels: size/L

#736 docs: add artifacthub badge
  README.md
  hack/config/update-readme/README.md.gotmpl
Labels: size/XS

#738 feat(infra-apps): upgrade kured from 2.15 to 2.16
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#739 fix(tracing-apps): upgrade opentelemetry-collector from 0.20.1 to 0.20.2
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/XS

#737 chore(deps): update helm-docs from 1.10.0 to 1.11.0
  .env
  .pre-commit-config.yaml
Labels: size/XS
