Repository adfinis/helm-charts, pull requests merged in 2022-08, with the labels that each got.

#763 fix(imagerefs): ghcr.io/adfinis is the new imagref
  charts/back8sup/Chart.yaml
  charts/back8sup/README.md
  charts/back8sup/values.yaml
  charts/caasperli/Chart.yaml
  charts/caasperli/README.md
  charts/caasperli/values.yaml
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
  charts/customer-center/values.yaml
  charts/huawei-csi-plugin/Chart.yaml
  charts/huawei-csi-plugin/README.md
  charts/huawei-csi-plugin/values.yaml
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
  charts/mopsos/values.yaml
Labels: size/M

#762 fix imageref
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
  charts/openshift-etcd-backup/values.yaml
Labels: size/XS

#756 feat(security-apps): update stackrox from 70.1.0 to 71.0.0
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#758 feat(argo-apps): update argo-rollouts from 2.17 to 2.18
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/XS

#765 chore(rmd): remove archived project
  charts/rmd/.helmignore
  charts/rmd/Chart.lock
  charts/rmd/Chart.yaml
  charts/rmd/README.md
  charts/rmd/ci/default-values.yaml
  charts/rmd/templates/NOTES.txt
  charts/rmd/templates/_helpers.tpl
  charts/rmd/templates/configmap.yaml
  charts/rmd/templates/cronjob.yaml
  charts/rmd/templates/deployment-rmd.yaml
  charts/rmd/templates/ingress.yaml
  charts/rmd/templates/job-dbmigrate.yaml
  charts/rmd/templates/secret-backend.yaml
  charts/rmd/templates/service.yaml
  charts/rmd/templates/tests/test-connection.yaml
  charts/rmd/values.yaml
Labels: size/XL

#766 chore(huawei-csi-plugin): remove unmaintained chart
  charts/huawei-csi-plugin/.helmignore
  charts/huawei-csi-plugin/Chart.yaml
  charts/huawei-csi-plugin/README.md
  charts/huawei-csi-plugin/ci/defaults-values.yaml
  charts/huawei-csi-plugin/docs/INSTALL.md
  charts/huawei-csi-plugin/templates/_helpers.tpl
  charts/huawei-csi-plugin/templates/configmap.yaml
  charts/huawei-csi-plugin/templates/daemonset-node.yaml
  charts/huawei-csi-plugin/templates/deployment-controller.yaml
  charts/huawei-csi-plugin/templates/rbac.yaml
  charts/huawei-csi-plugin/templates/serviceaccount.yaml
  charts/huawei-csi-plugin/values.yaml
Labels: size/XXL

#769 fix(openshift-etc-backup): update from 1.6.0 to 1.6.4
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/XS

#771 chore: update Helm from 3.8.0 to 3.9.3
  .env
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: size/XS

#772 fix(infra-apps): update cert-manager from 1.8 to 1.9
  charts/infra-apps/Chart.lock
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#773 feat(argoconfig): add ApplicationSet support
  charts/argoconfig/Chart.lock
  charts/argoconfig/Chart.yaml
  charts/argoconfig/README.md
  charts/argoconfig/templates/_applicationSet.yaml
Labels: size/S

#776 update loki-stack to version 2.7.*
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/XS

#775 chore(customer-center): update to v3.2.4
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS
