Repository adfinis/helm-charts, pull requests merged in 2022-03, with the labels that each got.

#586 chore(kube-prom-stack): update to 33.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#589 chore(argoRollouts): update to v2.10.*
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/XS

#585 feature(misc-apps): Add prom2teams to send alerts to Microsoft Teams
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/examples/prometheus-msteams.yaml
  charts/misc-apps/values.yaml
Labels: size/M

#591 feat(rmd): add tls option for email as env var
  charts/rmd/Chart.yaml
  charts/rmd/README.md
  charts/rmd/templates/configmap.yaml
  charts/rmd/values.yaml
Labels: size/XS

#587 chore(velero): update to 2.28.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#590 chore(argoCD): update to 3.35.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#592 fix(misc-apps): missing template for prometheus-msteams
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/templates/prometheus-msteams.yaml
Labels: size/M

#593 docs: make wording in pr template more clear
  .github/pull_request_template.md
Labels: size/XS

#594 feat(infra-apps): kube-prometheus-stack 33.2.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#600 chore(infra-apps): update kube-prometheus-stack to version 34.0.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#601 chore(infra-apps): update rbac-manager to v1.11.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#602 chore(infra-apps): update thanos to v10.1.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#603 chore(infra-apps): update kured to v2.12.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#604 chore(infra-apps): update argocd to 4.0.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#605 fix(infra-apps): bump argo-cd from 4.0.* to 4.1.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#609 feat(argo-apps): argo-rollouts v1.2.0 (chart 2.12)
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/XS

#613 barman: remove duplicate label
  charts/barman/Chart.yaml
  charts/barman/README.md
  charts/barman/templates/_helpers.tpl
Labels: size/XS

#612 feat(mopsos): add initial Chart
  CODEOWNERS
  README.md
  charts/mopsos/.helmignore
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/templates/NOTES.txt
  charts/mopsos/templates/_helpers.tpl
  charts/mopsos/templates/configmap.yaml
  charts/mopsos/templates/deployment.yaml
  charts/mopsos/templates/hpa.yaml
  charts/mopsos/templates/ingress.yaml
  charts/mopsos/templates/secret.yaml
  charts/mopsos/templates/service.yaml
  charts/mopsos/templates/serviceaccount.yaml
  charts/mopsos/templates/tests/test-connection.yaml
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
  charts/mopsos/tests/deployment_existingSecret_test.yaml
  charts/mopsos/tests/deployment_test.yaml
  charts/mopsos/tests/secret_basicauthusers_test.yaml
  charts/mopsos/tests/secret_existingSecret_test.yaml
  charts/mopsos/values.yaml
Labels: size/XL

#615 feature(barman): Add additional conf options
  charts/barman/Chart.yaml
  charts/barman/README.md
  charts/barman/templates/configmap-barman-backups.yaml
  charts/barman/templates/deployment.yaml
  charts/barman/values.yaml
Labels: size/S
