Repository adfinis/helm-charts, pull requests merged in 2022-02, with the labels that each got.

#546 feat(tracing-apps): install opentelemetry-collector
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/ci/default-values.yaml
  charts/tracing-apps/examples/opentelemetryCollector.yaml
  charts/tracing-apps/templates/opentelemetryCollector.yaml
  charts/tracing-apps/values.yaml
Labels: size/M

#547 feat(infra-apps): kube-prom-stack 31.0.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#551 feat(infra-apps): argo-cd 3.33.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#548 feat(chart-testing): introduce pluto
  .env
  docs/development.md
  hack/chart-testing/ct.yaml
  hack/pluto.sh
  hack/sh/deps/pluto.sh
Labels: size/M

#554 fix(vault-monitoring): remove unused values
  README.md
  charts/vault-monitoring/Chart.yaml
  charts/vault-monitoring/README.md
  charts/vault-monitoring/values.yaml
Labels: size/S

#570 feat(argo-apps): argocd-notifications 1.8
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/XS

#553 chore(back8sup): update to latest
  charts/back8sup/Chart.yaml
  charts/back8sup/README.md
  charts/back8sup/templates/cronjob.yaml
Labels: size/XS

#571 feat(tracing-apps): opentelemetry-collector 0.9
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/XS

#569 chore(lokiStack): update to 2.6.* #561
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/XS

#573 feat(infra-apps): kubeEventExporter 1.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#574 chore(security-apps): update vault to v0.19
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#577 chore(misc-apps): update chartmuseum to v3.6
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/XS

#578 chore(falco): update to 1.17.1 #565
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#576 chore(falcoExporter): update to version 0.8.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#579 feat(openshift-etcd-backup): update to 1.6.0
  README.md
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
  charts/openshift-etcd-backup/templates/cronjob.yaml
Labels: size/S

#575 feat(infra-apps): kubePrometheusStack 32.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#580 chore(customer-center): update to v3.2.1
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#581 feat(rbacdefinitions): new chart
  .env
  README.md
  charts/rbac-definitions/.helmignore
  charts/rbac-definitions/Chart.lock
  charts/rbac-definitions/Chart.yaml
  charts/rbac-definitions/README.md
  charts/rbac-definitions/ci/default-values.yaml
  charts/rbac-definitions/examples/clusterrolebinding.yaml
  charts/rbac-definitions/examples/enabled-and-disabled.yaml
  charts/rbac-definitions/examples/namespaceselector.yaml
  charts/rbac-definitions/templates/NOTES.txt
  charts/rbac-definitions/templates/_helpers.tpl
  charts/rbac-definitions/templates/rbacdefinitions.yaml
  charts/rbac-definitions/tests/__snapshot__/rbacdefinitions_test.yaml.snap
  charts/rbac-definitions/tests/rbacdefinitions_test.yaml
  charts/rbac-definitions/values.yaml
  hack/deploy/init.sh
Labels: size/L

#583 feat(infra-apps): bump jaeger-operator to 2.29 (operator version 1.31)
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/XS

#582 docs(infra-apps): document setting ingress as default class
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/examples/nginx-ingress-on-aks.yaml
  charts/infra-apps/examples/nginx-ingress.yaml
Labels: size/S
