Repository adfinis/helm-charts, pull requests merged in 2022-11, with the labels that each got.

#842 feat(infra-apps): update argo-cd from 5.8 to 5.12
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#846 fix(infra-apps): Update argo-cd from 5.12 to 5.13
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#847 feat(tracing-apps): Update jaeger-operator from 2.33.0 to 2.36.0
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/S

#848 feat(argo-apps): Update Argo Rollouts from 2.20 to 2.21
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/S

#843 fix(openshift-etcd-backup): update from 1.6.5 to 1.6.6
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/XS

#851 chore(timed): update timed-backend image tag
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/XS

#852 feat(infra-apps): upgrade kube-prometheus-stack from 40.1 to 41.7.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/L

#849 feat(logging-apps): update otel-collector from 0.20.2 to 0.38.1
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/L

#853 feat(security-apps): upgrade stackrox from 72.0 to 72.1
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#854 chore(thanos): mark as DEPRECATED
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#855 chore(fluentd): Update to 5.5.*
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/XS

#857 chore(kube-event-exporter): Update to 1.5.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#858 feat(infra-apps): upgrade from argo-cd 5.13.* to 5.14.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/L

#859 feat(infra-apps): upgrade ingress from 4.2.* to 4.4.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#880 feat(infra-apps): upgrade kured from 4.0.1 to 4.1.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#856 chore(filebeat): update to 8.5.1
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/S

#885 chore(opentelemetryCollector): update to 0.39.3
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/L

#884 chore(storage-apps): update minio to 5.0.1
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/values.yaml
Labels: size/S

#891 Update PR template adding the changelog as todo
  .github/pull_request_template.md
Labels: size/XS

#882 chore(security-apps): Update falco to v2.3.0
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#892 chore(gatekeeper): update to 3.10.0
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#887 feat(infra-apps): update kube-prometheus-stack to 42.0.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#888 feat(azure-apps): update promitorScraper to 2.9.0
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/M

#890 feat(misc-apps): update kube-downscaler to 0.6.0
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#893 chore(infra-apps): Update kube-prometheus-stack to v42.1.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#894 fix(security apps) : add template for oauth2-proxy
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/templates/oauth2-proxy.yaml
  charts/security-apps/values.yaml
Labels: size/M
