Repository adfinis/helm-charts, pull requests merged in 2022-07, with the labels that each got.

#741 chore: remove @michaelimfeld from CODEOWNERS
  CODEOWNERS
Labels: size/XS

#742 fix(mopsos): update mopsos from 0.3.6 to 0.3.7
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Labels: size/S

#746 chore(timed): update timed image tags
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#747 feat(security-apps): update falco from 1.19 to 1.20
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/examples/falco.yaml
  charts/security-apps/values.yaml
Labels: size/S

#750 fix(csi-secret-provider-class): update pause container from k8s.gcr.io/pause:3.4.1 to registry.k8s.io/pause:3.7
  charts/csi-secret-provider-class/Chart.yaml
  charts/csi-secret-provider-class/README.md
  charts/csi-secret-provider-class/tests/__snapshot__/dummydeployment_test.yaml.snap
  charts/csi-secret-provider-class/tests/__snapshot__/secretproviderclass_test.yaml.snap
  charts/csi-secret-provider-class/values.yaml
Labels: size/S

#748 feat(security-apps): add stackrox deployment
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/examples/stackrox.yaml
  charts/security-apps/templates/stackrox-central-services.yaml
  charts/security-apps/templates/stackrox-secured-cluster-services.yaml
  charts/security-apps/values.yaml
Labels: size/L

#752 fix(security-apps): use existing stackrox chart version
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/examples/stackrox.yaml
  charts/security-apps/values.yaml
Labels: size/M

#751 feat(infra-apps): add mimir chart to infra
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/ci/default-values.yaml
  charts/infra-apps/examples/mimir.yaml
  charts/infra-apps/templates/mimir.yaml
  charts/infra-apps/values.yaml
Labels: size/L

#753 docs: deprecation policy for app-of-apps components
  docs/argocd-app-of-apps.md
Labels: size/S

#754 feat(back8sup): add security contexts to cronjob
  charts/back8sup/Chart.yaml
  charts/back8sup/README.md
  charts/back8sup/templates/cronjob.yaml
  charts/back8sup/values.yaml
Labels: size/S

#757 fix(infra-apps): update argo-cd from 4.9 to 4.10
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#759 feat(tracing-apps): update jaeger-operator from 2.32.2 to 2.33.0
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/XS

#760 chore: remove @aziiee from CODEOWNERS
  CODEOWNERS
Labels: size/XS
