Repository adfinis/helm-charts, pull requests merged in 2022-09, with the labels that each got.

#778 fix: update openshift etcd backup from 1.6.4 to 1.6.5
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/XS

#779 updated upstream chart version
  charts/misc-apps/Chart.lock
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#781 feat(argo-apps): update argo-rollouts from 2.18 to 2.20
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/XS

#783 fix(back8sup): update from 0.7.9 to 0.7.10
  charts/back8sup/Chart.yaml
  charts/back8sup/README.md
Labels: size/XS

#784 feat(security-apps): upgrade dex to 2.34
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS

#782 feat(azure-apps): update promitor disco from 0.7 to 0.8 and scraper from 2.7 to 2.8
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/S

#785 chore(ci): update helm from 3.9.3 to 3.9.4
  .env
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: size/XS

#780 feat(infra-apps): update argo-cd from 4.10 to 5.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#806 feat(infra-apps): update velero from 2.30 to 2.31
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#805 feat(misc-apps): add argocd-apps chart
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/ci/default-values.yaml
  charts/misc-apps/examples/argocd-apps.yaml
  charts/misc-apps/templates/argocd-apps.yaml
  charts/misc-apps/values.yaml
Labels: size/M

#808 feat(infra-apps): Update kured to 3.0.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#811 fix(infra-apps): Update kured repo url
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#812 patch(infra-apps): Update Comments with new URL
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#813 feat(misc-apps): add KEDA
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/ci/default-values.yaml
  charts/misc-apps/examples/keda.yaml
  charts/misc-apps/templates/keda.yaml
  charts/misc-apps/values.yaml
Labels: size/M

#815 ci(helm): update to 3.10.0
  .env
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: size/XS

#809 feat(infra-apps): Update rbacManager to 1.13.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#814 feat(backup-apps): update barman from 0.8 to 0.9
  charts/backup-apps/Chart.yaml
  charts/backup-apps/README.md
  charts/backup-apps/values.yaml
Labels: size/XS

#821 feat(thanos): Update thanos to 11.5.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#820 feat(loki): Update loki to 2.8.*
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/XS

#816 chore(kps): update to 40.1.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS
