Repository adfinis/helm-charts, pull requests merged in 2022-01, with the labels that each got.

#508 fix(infra-apps): nginx annotation in ingress examples
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/examples/prometheus.yaml
Labels: size/S

#510 chore(timed-backend): update to v1.5.4
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/XS

#511 fix(timed): center total hours column in workreport
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/files/workreport.ots
Labels: size/XS

#509 feat(barman): `secret.create` option
  charts/barman/Chart.yaml
  charts/barman/README.md
  charts/barman/examples/barman.yaml
  charts/barman/templates/secret-pgpass.yaml
  charts/barman/values.yaml
Labels: size/L

#499 docs(app-of-apps): add info on app-of-apps chart structure
  docs/argocd-app-of-apps.md
Labels: size/M

#513 feat(argo-apps): argo-rollouts 2.9
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/XS

#514 feat(security-apps): falco-event-exporter 0.7
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/examples/falco-exporter.yaml
  charts/security-apps/values.yaml
Labels: size/S

#515 fix(security-apps): bump falco-exporter and not dex
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#516 chore: deprecate huawei-csi-plugin chart
  README.md
  charts/huawei-csi-plugin/Chart.yaml
  charts/huawei-csi-plugin/README.md
Labels: size/S

#518 feat(backup-apps): barman chart 0.5
  charts/backup-apps/Chart.yaml
  charts/backup-apps/README.md
  charts/backup-apps/values.yaml
Labels: size/XS

#519 chore(customer-center): update to 3.1.8
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/XS

#520 feat(infra-apps): argocd chart 3.30
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#483 feat(logging-apps): update fluentd helm chart to new version 4.4.*
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/XS

#521 feat(infra-apps): kube-prometheus-stack 30.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#535 Changing Version 3.5.0 of cephCsiRbd and cephCsiCephfs
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/values.yaml
Labels: size/S

#522 ci(helm-docs): update to 1.7.0
  .env
  .pre-commit-config.yaml
Labels: size/XS

#467 feat(azure-apps): azurekvcsiprovider-1.0
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/XS

#536 Changed the image versions
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/S

#534 feat(argocd-apps): Bump argocdNotifications to 1.7.*
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/XS

#538 feat(infra-apps): argo-cd chart 3.31
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#539 feat(timed): add tls option for email as env var
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/configmap-backend.yaml
  charts/timed/values.yaml
Labels: size/XS

#540 fix(timed): update ingress api version to v1
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/ingress.yaml
Labels: size/XS

#537 filebeat version update
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/XS

#541 fix(timed): fix ingress template for apiVersion v1
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/ingress.yaml
  charts/timed/templates/service-backend.yaml
  charts/timed/templates/service-frontend.yaml
Labels: size/M

#543 fix(timed): add missing `pathType` in ingress template
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/ingress.yaml
Labels: size/XS

#544 feat(infra-apps): cert-manager 1.7
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#545 feat(infra-apps): bump argocd from 3.31 to 3.32
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS
