Repository adfinis/helm-charts, pull requests merged in 2022-04, with the labels that each got.

#619 fix(chart-testing): update target branch
  hack/chart-testing/ct-install.yaml
  hack/chart-testing/ct.yaml
Labels: size/XS

#620 chore(argoconfig): update commons from 0.0.6 to 0.0.7
  charts/argoconfig/Chart.lock
  charts/argoconfig/Chart.yaml
  charts/argoconfig/README.md
Labels: size/S

#621 chore(*-apps): update argoconfig from 0.7.4 to 0.7.6
  charts/argo-apps/Chart.lock
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/azure-apps/Chart.lock
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/backup-apps/Chart.lock
  charts/backup-apps/Chart.yaml
  charts/backup-apps/README.md
  charts/infra-apps/Chart.lock
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/logging-apps/Chart.lock
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/misc-apps/Chart.lock
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/security-apps/Chart.lock
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/storage-apps/Chart.lock
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/tracing-apps/Chart.lock
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
Labels: size/L

#622 chore(rbac-definitions): update common from 0.0.6 to 0.0.7
  charts/rbac-definitions/Chart.lock
  charts/rbac-definitions/Chart.yaml
  charts/rbac-definitions/README.md
  charts/rbac-definitions/tests/__snapshot__/rbacdefinitions_test.yaml.snap
Labels: size/S

#624 chore(cert-manager-issuers): update common from 0.0.6 to 0.0.7
  charts/cert-manager-issuers/Chart.lock
  charts/cert-manager-issuers/Chart.yaml
  charts/cert-manager-issuers/README.md
  charts/cert-manager-issuers/tests/__snapshot__/clusterissuers_test.yaml.snap
  charts/cert-manager-issuers/tests/__snapshot__/issuers_test.yaml.snap
Labels: size/M

#618 feat(barman): update from 2.17 to 2.19
  charts/barman/Chart.yaml
  charts/barman/README.md
Labels: size/XS

#626 chore(csi-secret-provider-class): update common from 0.0.6 to 0.0.7
  charts/csi-secret-provider-class/Chart.lock
  charts/csi-secret-provider-class/Chart.yaml
  charts/csi-secret-provider-class/README.md
  charts/csi-secret-provider-class/tests/__snapshot__/dummydeployment_test.yaml.snap
  charts/csi-secret-provider-class/tests/__snapshot__/secretproviderclass_test.yaml.snap
Labels: size/S

#625 fix(timed): update meta data in workreport
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/files/workreport.ots
Labels: size/XS

#627 chore(timed): update image versions to latest published tags
  README.md
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#628 feat(infra-apps): bump argo-cd from 4.2 to 4.5
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#629 feat(tracing-apps): update opentelemetry-collector from 0.9 to 0.12
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/XS

#630 feat(infra-apps): update velero chart from 2.28 to 2.29
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#631 fix(barman): Adjust slot-creation
  charts/barman/Chart.yaml
  charts/barman/README.md
  charts/barman/templates/configmap-barman-cron.yaml
  charts/barman/templates/deployment.yaml
  charts/barman/values.yaml
Labels: size/M

#632 chore(kured): update to use chart version 2.13.*
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#607 fix(rmd): move rmd secrets
  charts/rmd/Chart.yaml
  charts/rmd/README.md
  charts/rmd/templates/_helpers.tpl
  charts/rmd/templates/configmap.yaml
  charts/rmd/templates/cronjob.yaml
  charts/rmd/templates/deployment-rmd.yaml
  charts/rmd/templates/job-dbmigrate.yaml
  charts/rmd/templates/secret-backend.yaml
  charts/rmd/values.yaml
Labels: size/M

#636 chore(mopsos): bump from 0.3.0 to 0.3.2
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Labels: size/S

#633 chore(huawei-csi-plugin): annotate image to disable security scanning
  charts/huawei-csi-plugin/.helmignore
  charts/huawei-csi-plugin/Chart.yaml
  charts/huawei-csi-plugin/README.md
  charts/huawei-csi-plugin/ci/defaults-values.yaml
  charts/huawei-csi-plugin/docs/INSTALL.md
  charts/huawei-csi-plugin/templates/_helpers.tpl
  charts/huawei-csi-plugin/templates/configmap.yaml
  charts/huawei-csi-plugin/templates/daemonset-node.yaml
  charts/huawei-csi-plugin/templates/deployment-controller.yaml
  charts/huawei-csi-plugin/templates/rbac.yaml
  charts/huawei-csi-plugin/templates/serviceaccount.yaml
  charts/huawei-csi-plugin/values.yaml
  hack/chart-testing/ct-install.yaml
Labels: size/XXL

#638 feat(mopsos): add Grafana deployment
  charts/mopsos/Chart.lock
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/ci/default-values.yaml
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
  charts/mopsos/tests/secret_basicauthusers_test.yaml
  charts/mopsos/values.yaml
  hack/chart-testing/ct-install.yaml
  hack/chart-testing/ct.yaml
Labels: size/M

#640 fix(mopsos): use secureJson for the datasource
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
  charts/mopsos/values.yaml
Labels: size/S

#641 feat(mopsos): add default dashboard
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/dashboards/mopsos-data.json
  charts/mopsos/templates/configmap-dashboard.yaml
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
  charts/mopsos/values.yaml
Labels: size/L

#642 feat(mopsos): allow selecting multiple clusters/apps
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/dashboards/mopsos-data.json
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Labels: size/L

#645 feat(mopsos): set default home dashboard
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
  charts/mopsos/values.yaml
Labels: size/XS

#646 fix(mopsos): update mopsos from 0.3.2 to 0.3.3
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Labels: size/S

#647 fix(mopsos): move misplaced grafana.ini section
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
  charts/mopsos/values.yaml
Labels: size/S

#648 feat/updated timed backend ref
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/XS

#650 feat(infra-apps): update nginx-ingress from 4.0 to 4.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS
