Repository adfinis/helm-charts, pull requests merged in 2022-10, with the labels that each got.

#823 feat(security-apps): update dex chart to 0.12.0
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS, hacktoberfest-accepted

#824 chore(gatekeeper): update to 3.9.*
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/XS, hacktoberfest-accepted

#826 feat(timed-backend): add probes for django hurricane deployment
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/deployment-backend.yaml
  charts/timed/values.yaml
Labels: size/M

#827 fix(timed-backend): increase startup probe failture threshold
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/deployment-backend.yaml
  charts/timed/values.yaml
Labels: size/XS

#830 fix(security-apps): valid markdown for links in README
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#831 feat(security-apps): update stackrox from 71.0.0 to 72.0.0
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#834 chore(misc/metallb): update to 0.13.x
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/XS, hacktoberfest-accepted

#832 chore(security/vault): update to 0.22.0
  charts/security-apps/Chart.lock
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S, hacktoberfest-accepted

#833 chore(storage/ceph-csi): update to 3.7.1
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/values.yaml
Labels: size/S, hacktoberfest-accepted

#835 chore(infra/mimir): update to 3.1.x
  charts/infra-apps/Chart.lock
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#837 chore(infra-apps): update cert-manager to 1.10.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: hacktoberfest-accepted

#829 feat(argocd): move ui extensions to argocd-apps and fix argocd-apps
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#807 feat(azure-apps): Update azureKvCsiProvider
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/XS, hacktoberfest-accepted

#836 feat(storage-apps): add csi-driver-smb
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/examples/csi-driver-smb.yaml
  charts/storage-apps/templates/csi-driver-smb.yaml
  charts/storage-apps/values.yaml
Labels: size/M, hacktoberfest-accepted

#838 feat(infra-apps): Update Argo CD chart from 5.6 to 5.8
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#839 fix(infra-apps): proper strings in changelog annotations
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
Labels: size/S

#828 feat(timed-backend): add env vars to configure hurricane
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/configmap-backend.yaml
  charts/timed/templates/deployment-backend.yaml
  charts/timed/values.yaml
Labels: size/S

#844 chore: lint artifacthub annotations with ah lint
  .env
  .github/workflows/test.yaml
  docs/development.md
  hack/chart-testing/ct.yaml
  hack/sh/deps/ah.sh
  hack/sh/deps/pluto.sh
Labels: size/S

#845 chore(ci): hacky fix for ci fail
  hack/chart-testing/ct.yaml
  hack/sh/deps/pluto.sh
Labels: size/XS
