Repository adfinis/helm-charts, pull requests merged in 2022-12, with the labels that each got.

#895 feat(timed): add cronjob for budget check
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#899 chore(sec-apps/secrets-store-csi-driver): update to version 1.2.4
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/M

#900 doc(github/pr): add info about example PR for artifacthub changes
  .github/pull_request_template.md
Labels: size/XS

#898 feat(misc-apps): update chartmuesum-chart
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#897 feat(security-apps): update falcoExporter to appVersion 0.8.0
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/M

#902 chore(huawei-csi-plugin): remove last remnants of the chart
  CODEOWNERS
  hack/chart-testing/ct-install.yaml
Labels: size/XS

#903 chore(vault-csi-provider): remove last remnants of the chart
  CODEOWNERS
Labels: size/XS

#905 feat: [barman] add init containers
  charts/barman/Chart.yaml
  charts/barman/README.md
  charts/barman/templates/deployment.yaml
  charts/barman/values.yaml
Labels: size/M

#906 feat(timed): add env var for redmine build project
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/configmap-backend.yaml
  charts/timed/values.yaml
Labels: size/S

#912 chore(infra-apps): bump velero to 2.32.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#911 feat: add grafana agent operator
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/ci/default-values.yaml
  charts/misc-apps/examples/grafana-agent-operator.yaml
  charts/misc-apps/values.yaml
Labels: size/M

#914 chart version bump to new minor version
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#915 fix(grafana-agent-operator): Add template file
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/templates/grafana-agent-operator.yaml
Labels: size/M

#909 chore(customer-center): update appVersion to v3.2.5
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/S

#916 feat(infra-apps): update argo-cd from 5.14.1 to 5.16.10
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#917 feat(infra-apps): update kube-event-exporter chart from 2.1.1 to 2.1.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/L

#918 feat(misc-apps): update kube-downscaler chart from 0.6.0 to 0.7.0
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#919 chore(timed): update timed-frontend image tag to v3.0.0-rc1
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S
