Repository adfinis/helm-charts, pull requests merged in 2023-10, with the labels that each got.

#1123 feat(misc-apps): Update argocd-apps chart from 1.0.0 to 1.4.1
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/M

#1126 chore(downscaler): Updated downscaler from 0.7.1 to 0.7.3
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#1128 fix(infra-apps): Udpate Argo CD chart from 5.46.3 to 5.46.7
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1129 chore(promitorResourceDiscovery): update from 0.9.0 to 0.11.0
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/M

#1130 chore(promitorScraper): update to version 2.12.0
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/S

#1124 feat(infra-apps): Update kubePrometheusStack from 49.2.0 to 51.2.0 (#…
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1127 feat(azure-apps): Update azureKvCsiProvider from 1.3.* to 1.4.1 (#1104)
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/M

#1132 feat(misc-apps): update KEDA chart from 2.10.1 to 2.12.0
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/M

#1133 feat(infra-apps): Update kured from 4.2.0 to 5.2.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1135 feat(misc-apps): Update chartmuseum from 3.9.2 to 3.10.1
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/L

#1137 fix(infra-apps): upgrade ingress-nginx chart to 4.8.3
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M
