Repository adfinis/helm-charts, pull requests merged in 2023-06, with the labels that each got.

#1052 feat(infra-apps): update Argo CD from 3.7.1 to 3.7.3
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1053 feat(timed): activate update_project_expenditure job
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#1054 chore(timed): bump backend image tag to v3.0.7
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#1055 feat(infra-apps): Update argo-cd from 3.7.3 to 3.7.5
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1056 feat(security-apps): add kyverno and kyverno-policies deployments
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/ci/default-values.yaml
  charts/security-apps/examples/kyverno.yaml
  charts/security-apps/templates/kyverno-policies.yaml
  charts/security-apps/templates/kyverno.yaml
  charts/security-apps/values.yaml
Labels: size/L

#1057 feat(infra-apps): Update cert-manager from 1.12.0 to 1.12.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1059 chore(security-apps): update Dex chart to 0.14.2
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#1060 infra-apps: update mimir-distributed
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/ci/default-values.yaml
Labels: size/M

#1061 infra-apps: actually update mimir-distributed
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/XS

#1062 feat(hedgedoc): Update to 1.9.8
  charts/hedgedoc/Chart.yaml
  charts/hedgedoc/README.md
  charts/hedgedoc/templates/deployment.yaml
Labels: size/S
