Repository adfinis/helm-charts, pull requests merged in 2023-12, with the labels that each got.

#1156 feat(azure-apps): introduce azure-workload-identity-webhook deployment
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/ci/default-values.yaml
  charts/azure-apps/examples/azure-workload-identity-webhook.yaml
  charts/azure-apps/templates/azure-workload-identity-webhook.yaml
  charts/azure-apps/values.yaml
Labels: size/L

#1152 feat(infra-apps): Update kube-prometheus-stack chart from 51.2.0 to 54.2.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/L

#1151 Added Kubernetes etcd backup chart
  README.md
  charts/kubernetes-etcd-backup/Chart.yaml
  charts/kubernetes-etcd-backup/README.md
  charts/kubernetes-etcd-backup/templates/_helpers.tpl
  charts/kubernetes-etcd-backup/templates/additionalPrometheusRules.yaml
  charts/kubernetes-etcd-backup/templates/configmap.yaml
  charts/kubernetes-etcd-backup/templates/cronjob.yaml
  charts/kubernetes-etcd-backup/templates/prometheusrule.yaml
  charts/kubernetes-etcd-backup/templates/pvc.yaml
  charts/kubernetes-etcd-backup/values.yaml
Labels: size/L

#1162 chore(openshift-etcd-backup): update openshift-etcd-backup image to v1.7.0
  README.md
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1163 chore(etcd-backup): bump to latest release 1.0.4
  charts/kubernetes-etcd-backup/Chart.yaml
  charts/kubernetes-etcd-backup/README.md
  charts/kubernetes-etcd-backup/values.yaml
Labels: size/S

#1165 fix(keycloak-operator): Update keycloak from 23.0.1 to 23.0.2
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1166 chore(openshift-etcd-backup): update openshift-etcd-backup image to v1.7.1
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1167 fix(infra-apps): Update Argo CD from 2.9.1 to 2.9.3
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1168 ci(release): add skip_existing to chart-releaser action
  .github/workflows/release.yaml
Labels: size/XS

#1169 chore(logging-apps): update Loki to 2.9.3 / Loki chart to 5.41.4
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/S

#1170 feat(cronjob): add annotations support in pod template
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
  charts/openshift-etcd-backup/templates/cronjob.yaml
  charts/openshift-etcd-backup/values.yaml
Labels: size/S

#1171 chore(infra-apps): bump Velero to helm chart 5.2.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S
