Repository adfinis/helm-charts, pull requests merged in 2023-09, with the labels that each got.

#1091 feat(infra-apps): Update Argo CD from 2.8.0 to 2.8.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/L

#1092 feat(infra-apps): bump infra-apps to 0.173.0 to upgrade KPS to 49.2.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/L

#1094 feat(infra-apps): Update cert-manager from 1.12.3 to 1.12.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/L

#1095 feat(infra-apps): Update Argo CD from 2.8.2 to 2.8.3
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1096 feat(infra-apps): update cert-manager from 1.12.4 to 1.13.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1097 feat(infra-apps): Update Argo CD from 2.8.3 to 2.8.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1098 feat(argo-apps): Update Argo Rollouts from 1.5.1 to 1.6.0
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/S

#1100 feat(storage-apps): update MinIO from 5.0.8 to 5.0.13
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/values.yaml
Labels: size/S

#1099 feat(misc-apps): Update OpenCost from 1.103.1 to 1.105.2
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/M

#1101 feat(infra-apps): Update cert-manager from 1.13.0 to 1.13.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1102 fix(keycloak-operator): proper indent for imagePullSecret in operand
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M
