Repository adfinis/helm-charts, pull requests merged in 2023-07, with the labels that each got.

#1064 chore(customer-center): update to v3.2.6
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/S

#1065 chore: update CODEOWNERS for customer-center
  CODEOWNERS
Labels: size/XS

#1066 feat(infra-apps): update Argo CD from 2.7.4 to 2.7.7
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1071 feat(argo-apps): Update argo-rollouts from 2.26.1 to 2.31.0
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/S

#1072 feat(security-apps): update StackRox from 3.x to 4.x
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/examples/stackrox.yaml
  charts/security-apps/values.yaml
Labels: size/M

#1070 Bump nginx ingress to 4.7.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1050 feat(security-apps): bump secrets-store-csi-driver to 1.3.3
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#1068 feat(keycloak-operator): update Keycloak from 21.1.0 to 22.0.0
  README.md
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/crds/keycloakrealmimports.k8s.keycloak.org-v1.yml
  charts/keycloak-operator/crds/keycloaks.k8s.keycloak.org-v1.yml
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
  charts/keycloak-operator/values.yaml
Labels: size/L

#1073 chore(thanos): make fail
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/ci/default-values.yaml
  charts/infra-apps/templates/thanos.yaml
  docs/argocd-app-of-apps.md
Labels: size/M
