Repository adfinis/helm-charts, pull requests merged in 2023-02, with the labels that each got.

#932 feat(tracing-apps): update jaeger-operator chart from 2.37.0 to 2.39.0
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/S

#946 chore(timed): update timed-frontend image tag to v3.0.0-rc6
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#947 feat(tracing-apps): update otel-collector from 0.39.3 to 0.47.3
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/M

#948 chore(timed): update backend image tag from v3.0.0-rc7 to v3.0.0-rc8
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#949 feat(misc-apps): update keda from 2.8 to 2.9.3
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#953 misc-apps/signalilo: update chart to 0.10.0
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#954 fix(tracing-apps): use a properly published version of the otel-collector chart
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/M

#955 chore(timed): update backend image tag
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#957 feat(misc-apps/signalilo): update chart to 0.10.1
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#958 feat(timed): add buildProject value for backend
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/configmap-backend.yaml
  charts/timed/values.yaml
Labels: size/S

#959 chore(timed): update timed-frontend image tag to v3.0.0-rc7
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#960 fix(infra-apps): Update Argo CD from 2.6.0 to 2.6.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#961 chore(timed): update backend image tag
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#962 feat(infra-apps): Update nginx-ingress chart from 4.4.0 to 4.5.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#963 chore(timed): update backend image tag to v3.0.0-rc11
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#964 feat(timed): support unmanaged secret via backend.existingSecret value
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/deployment-backend.yaml
  charts/timed/templates/secret-backend.yaml
  charts/timed/values.yaml
Labels: size/S

#966 chore(timed): update timed-frontend image tag to v3.0.0-rc9
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#967 chore(timed): update timed-frontend image tag to v3.0.0-rc10
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#969 chore(timed): update timed-frontend image tag to v3.0.0-rc11
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#970 feat(infra-apps): Update Argo CD from 2.6.1 to 2.6.2 (chart from 5.20.4 to 5.22.1)
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#971 chore(timed): update timed-backend image tag to v3.0.0-rc12
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#973 chore(timed): update timed-frontend image tag to v3.0.0-rc.13
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#965 chore: add dev-devops group to CODEOWNERS for timed and osschallenge charts
  CODEOWNERS
Labels: size/XS

#974 chore(timed): update backend image tag to v3.0.0-rc13
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#976 chore(openshift-etcd-backup): update to 1.6.11
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#977 docs: hint at requiring an issue before adding new charts
  .github/pull_request_template.md
  README.md
  hack/config/update-readme/README.md.gotmpl
Labels: size/XS

#979 fix(timed): added missing command option
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#980 chore(timed): update backend and frontend image tags
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#981 fix(hedgedoc): Make persistent storage work
  charts/hedgedoc/Chart.yaml
  charts/hedgedoc/README.md
  charts/hedgedoc/templates/deployment.yaml
Labels: size/S

#982 fix(hedgedoc): Fix storageClass
  charts/hedgedoc/Chart.yaml
  charts/hedgedoc/README.md
  charts/hedgedoc/templates/pvc.yaml
Labels: size/XS

#983 chore(timed): update frontend and backend image tags
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#984 chore(timed): update timed backend image tag
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S
