Repository adfinis/helm-charts, pull requests merged in 2023-05, with the labels that each got.

#1002 feat: init keycloak-operator chart
  README.md
  charts/keycloak-operator/.helmignore
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/ci/default-values.yaml
  charts/keycloak-operator/ci/operand-values.yaml
  charts/keycloak-operator/crds/keycloakrealmimports.k8s.keycloak.org-v1.yml
  charts/keycloak-operator/crds/keycloaks.k8s.keycloak.org-v1.yml
  charts/keycloak-operator/templates/NOTES.txt
  charts/keycloak-operator/templates/_helpers.tpl
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/templates/keycloak/keycloakrealmimport.yaml
  charts/keycloak-operator/templates/operator/clusterrole.yaml
  charts/keycloak-operator/templates/operator/deployment.yaml
  charts/keycloak-operator/templates/operator/rolebinding.yaml
  charts/keycloak-operator/templates/operator/roles.yaml
  charts/keycloak-operator/templates/operator/service.yaml
  charts/keycloak-operator/templates/operator/serviceaccount.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
  charts/keycloak-operator/tests/default_test.yaml
  charts/keycloak-operator/tests/operand_test.yaml
  charts/keycloak-operator/values.yaml
Labels: size/XXL

#1030 feat(infra-apps): update argo-cd chart from 5.28.1 to 5.29.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1034 feat(infra-apps): update kube-prometheus-stack chart from 45.9.1 to 45.23.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1029 feat(security-apps): Update vault chart from 0.22.* to 0.24.1
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/M

#1037 feat(infra-apps): update Argo CD from 2.6.7 to 2.7.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1038 feat(infra-apps): Update Argo CD from 2.7.0 to 2.7.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1035 feat(misc-apps): update argocd-apps chart from 0.0.9 to 1.0.0
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#1031 fix(argo-apps): update argo-rollouts chart from 2.26.0 to 2.26.1
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/S

#1032 feat(azure-apps): update promitor scraper to v2.10 & resource discovery to v0.9.0
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/M

#1027 feat(misc-apps): add OpenCost chart
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/ci/default-values.yaml
  charts/misc-apps/examples/opencost.yaml
  charts/misc-apps/templates/opencost.yaml
  charts/misc-apps/values.yaml
Labels: size/M

#1033 fix(logging-apps): update loki-stack chart from 2.9.9 to 2.9.10
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/S

#1036 feat(tracing-apps): update jaeger-operator from 1.42.0 to 1.43.0
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/M

#1045 ci(test):. Only run on PR
  .github/workflows/test.yaml
Labels: size/XS

#1043 fix(keycloak-operator): allow disabling ingress
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1046 feat(infra-apps): bump velero to latest 4.0.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1047 feat(infra-apps): update cert-manager from 1.11.1 to 1.12.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1048 Update openshift-etcd-backup to 1.6.14
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1049 chore(timed): bump backend image tag
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S
