Repository adfinis/helm-charts, pull requests merged in 2023-08, with the labels that each got.

#1075 chore(timed): update frontend image tag to v3.2.0
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#1076 feat(infra-apps): Update Argo CD from 2.7.6 to 2.7.10
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1077 fix(keycloak-operator): db secret indentation
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1079 feat(argo-apps): Update from from 1.5.0 to 1.5.1
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/M

#1078 feat(infra-apps): update cert-manager from 1.12.2 to 1.12.3
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1082 feat(misc-apps): update signalilo from 0.13.0 to 0.14.0
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/S

#1084 chore(timed): update frontend image tag to v3.2.2
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#1085 feat(infra-apps): Update Argo CD from 2.7.8 to 2.8.0 🥳
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1086 fix(infra-apps): Update Argo CD from 2.7.11 to 2.8.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1088 chore(openshift-etcd-backup): update openshift-etcd-backup image to v1.6.15
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1089 chore: Bump hedgedoc to 1.9.9
  charts/hedgedoc/Chart.yaml
  charts/hedgedoc/README.md
Labels: size/S

#1080 feat(tracing-apps): Update otel-collector from 0.75.0 to 0.82.0
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/examples/opentelemetryCollector.yaml
  charts/tracing-apps/values.yaml
Labels: size/M

#1083 feat(storage-apps): Update MinIO from RELEASE.2022-11-11T03-44-20Z to RELEASE.2023-04-13T03-08-07Z
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/values.yaml
Labels: size/S

#1090 feat(infra-apps): update kube-prometheus-stack chart from 45.23.0 to 48.3.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/L
