Repository adfinis/helm-charts, pull requests merged in 2023-01, with the labels that each got.

#921 chore(ci): upgrade Helm from 3.10.0 to 3.10.3
  .env
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: size/XS

#920 feat(infra-apps): upgrade argo-cd from 5.16.10 to 5.16.13
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#922 chore(k8s-event-exporter): update GH repo
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#923 chore(timed): update timed-backend image tag to v3.0.0-rc7
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#925 chore(ci): replace set-output with modern echo to $GITHUB_OUTPUT
  .github/workflows/test.yaml
Labels: size/XS

#926 feat(security-apps): update Stackrox from 3.72.1 to 3.73.1
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/M

#930 feat(infra-apps): update kube-prometheus-stack from 42.1.0 to 44.2.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#931 feat(infra-apps): update argo-cd from 5.15.13 to 5.17.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#928 Improve documentation regarding artifacthub.io annotations
  .github/pull_request_template.md
  README.md
  docs/development.md
  hack/config/update-readme/README.md.gotmpl
Labels: size/M

#934 fix(mopsos): update grafana from 6.25.* to 6.50.2
  charts/mopsos/Chart.lock
  charts/mopsos/Chart.yaml
  charts/mopsos/README.md
  charts/mopsos/tests/__snapshot__/deployment_test.yaml.snap
Labels: size/S

#933 chore(timed): update timed-frontend image tag to v3.0.0-rc3
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#935 feat(infra-apps): update cert-manager from 1.10 to 1.11.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#937 chore(timed): update timed-frontend image tag to v3.0.0-rc5
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#929 feat(timed): add ingress.ingressClassName value
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/templates/ingress.yaml
  charts/timed/values.yaml
Labels: size/S

#938 feat(infra-apps): update kube-event-exporter from 2.1.4 to 2.1.6
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#939 feat(infra-apps): Update argo-cd chart from 5.17.4 to 5.19.12 (contains argo-cd security patches!)
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#940 feat(infra-apps): update kured from 4.1.0 to 4.2.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#941 feat(infra-apps): update velero chart from 2.32.4 to 3.1.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#942 feat(infra-apps): update kube-prometheus-exported from 44.2.1 to 44.3.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#944 feat(backup-apps): update barman chart from 0.9.* to 0.10.0
  charts/backup-apps/Chart.yaml
  charts/backup-apps/README.md
  charts/backup-apps/values.yaml
Labels: size/S

#943 feat(argo-apps): update argo-rollouts chart from 2.21.* to 2.22.2
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/S
