Repository adfinis/helm-charts, pull requests merged in 2023-11, with the labels that each got.

#1125 chore(logging-apps): update fluentBit to 0.39.0
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/M

#1140 chore(keycloak-operator): bump keycloak version to 22.0.5
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1141 feat(security-apps): Update Vault Chart from 0.24.1 to 0.26.1
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#1138 feat(infra-apps): Update Argo CD from 2.8.4 to 2.8.5
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1144 Feat/security apps/update stackrox 4.2.2
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#1145 feat(infra-apps): Update Argo CD from 2.8.5 to 2.9.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1136 chore(misc-apps): pin metallb to 1.13.11 instead of wildcarding the patch version
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/M

#1147 feat(logging-apps): replace loki-stack with loki and promtail
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/ci/default-values.yaml
  charts/logging-apps/examples/loki-stack.yaml
  charts/logging-apps/examples/loki.yaml
  charts/logging-apps/examples/promtail.yaml
  charts/logging-apps/templates/loki.yaml
  charts/logging-apps/templates/promtail.yaml
  charts/logging-apps/values.yaml
Labels: size/L

#1148 chore(openshift-etcd-backup): update openshift-etcd-backup image to v1.6.17
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1149 feat(infra-apps): Update Argo CD from 2.9.0 to 2.9.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1150 fix(infra-apps): Update cert-manager from 1.13.1 to 1.13.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1131 feat(velero): bump helm chart from 4.0.2 to 5.1.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1153 chore(security-apps)!: Bump CSI-Secrets-Driver and Vault Chart version
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/M
