Repository adfinis/helm-charts, pull requests merged in 2024-03, with the labels that each got.

#1207 fix(openshift-etcd-backup): fix issue while using either S3 or NFS
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
  charts/openshift-etcd-backup/templates/configmap.yaml
  charts/openshift-etcd-backup/templates/secret.yaml
Labels: size/XS

#1210 chore(openshift-etcd-backup): update openshift-etcd-backup image to v1.8.5
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1211 feat(infra-apps): Update Argo CD from 2.10.3 to 2.10.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M
