Repository adfinis/helm-charts, pull requests merged in 2024-09, with the labels that each got.

#1306 chore(caasperli): Remove chart
  charts/caasperli/.helmignore
  charts/caasperli/Chart.yaml
  charts/caasperli/README.md
  charts/caasperli/ci/prometheus-values.yaml
  charts/caasperli/grafana/dashboards/caasperli-frontend.json
  charts/caasperli/templates/NOTES.txt
  charts/caasperli/templates/_helpers.tpl
  charts/caasperli/templates/deployment.yaml
  charts/caasperli/templates/grafana/configmap-dashboard.yaml
  charts/caasperli/templates/hpa.yaml
  charts/caasperli/templates/ingress.yaml
  charts/caasperli/templates/prometheus/podmonitor.yaml
  charts/caasperli/templates/prometheus/servicemonitor.yaml
  charts/caasperli/templates/service.yaml
  charts/caasperli/templates/serviceaccount.yaml
  charts/caasperli/templates/tests/test-connection.yaml
  charts/caasperli/values.yaml
Labels: size/XXL

#1307 fix: optional backchannelDynamic and update to 25.0.4
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1309 chore(openshift-etcd-backup): update image to v1.8.11
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1310 fix(keycloak): correctly set the httpManagement.port variable
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1311 fix(keycloak-operator): Deploy operator by default
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
  charts/keycloak-operator/values.yaml
Labels: size/M

#1312 chore(logging-apps): Update Loki from 3.0.0 to 3.1.1
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/M

#1314 chore(keycloak): update to v25.0.5
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1315 chore: fix link in PR template
  .github/pull_request_template.md
Labels: size/XS

#1313 chore(hedgedoc): Bump hedgedoc version to 1.10.0
  README.md
  charts/hedgedoc/Chart.yaml
  charts/hedgedoc/README.md
Labels: size/S

#1316 feat: Add operator.deploymentAnnotation value
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/templates/operator/deployment.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
  charts/keycloak-operator/values.yaml
Labels: size/M

#1317 Only create service with serviceMonitor
  charts/vault-monitoring/Chart.yaml
  charts/vault-monitoring/README.md
  charts/vault-monitoring/templates/service.yaml
Labels: size/S

#1318 feat(infra-apps): Update RBAC Manager from 1.8.0 to 1.9.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1319 Check serviceMonitor.create for ConfigMap and Endpoint
  charts/vault-monitoring/.Chart.yaml.swp
  charts/vault-monitoring/Chart.yaml
  charts/vault-monitoring/README.md
  charts/vault-monitoring/ci/default-values.yaml
  charts/vault-monitoring/templates/configmap.yaml
  charts/vault-monitoring/templates/endpoint.yaml
Labels: size/S

#1320 feat(hedgedoc): customize liveness and readiness probes
  charts/hedgedoc/Chart.yaml
  charts/hedgedoc/README.md
  charts/hedgedoc/templates/deployment.yaml
  charts/hedgedoc/values.yaml
Labels: size/M

#1321 chore: update keycloak to v25.0.6
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1322 fix(kubernetes-etcd-backup): bump appVersion to v1.2.0
  README.md
  charts/kubernetes-etcd-backup/Chart.yaml
  charts/kubernetes-etcd-backup/README.md
  charts/kubernetes-etcd-backup/values.yaml
Labels: size/S

#1323 fix(infra-apps): Update Argo CD from 2.12.0 to 2.12.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M
