Repository adfinis/helm-charts, pull requests merged in 2024-12, with the labels that each got.

#1344 chore(infra-apps): update mimir chart from 5.4.0 to 5.5.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1345 chore(infra-apps): update kured chart from 5.4.5 to 5.5.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1346 chore(infra-apps): update velero chart to 8.1.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1351 fix(etcd-backup): disallow concurrent job runs
  charts/kubernetes-etcd-backup/Chart.yaml
  charts/kubernetes-etcd-backup/README.md
  charts/kubernetes-etcd-backup/templates/cronjob.yaml
Labels: size/S

#1352 fix(customer-center): admins and employees should redirect to list en…
  charts/customer-center/Chart.yaml
  charts/customer-center/README.md
Labels: size/S

#1354 fix(keycloak): don't quote poolMinSize value
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: bug, size/M

#1356 chore: upgrade oauth2-proxy to 7.8.2
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/M
