Repository adfinis/helm-charts, pull requests merged in 2024-02, with the labels that each got.

#1193 fix(infra-apps): Update Argo CD from 2.9.4 to 2.9.5
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1196 feat(vault-monitoring): make bearerTokenFile optional
  charts/vault-monitoring/Chart.yaml
  charts/vault-monitoring/README.md
  charts/vault-monitoring/templates/servicemonitor.yaml
  charts/vault-monitoring/values.yaml
Labels: size/S

#1197 feat(infra-apps): Update Argo CD from 2.9.5 to 2.10.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1177 chore: Update pluto from 5.3.4 to 5.19.0
  .env
Labels: size/XS

#1183 fix(security-apps): Update csi-secrets-driver from 1.4.0 to 1.4.1
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/M

#1184 fix(keycloak-operator): Update from 23.0.2 to 23.0.4
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1186 chore(azure-apps): fix azureWorkloadIdentityWebhook values in README.md
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/S

#1189 feat(logging-apps): Update loki chart from 5.41.4 to 5.41.8
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/S

#1199 add optional authentication
  charts/vault-monitoring/Chart.yaml
  charts/vault-monitoring/README.md
  charts/vault-monitoring/examples/values.yaml
  charts/vault-monitoring/templates/configmap.yaml
  charts/vault-monitoring/templates/servicemonitor.yaml
  charts/vault-monitoring/values.yaml
Labels: size/S

#1200 chore(timed): update frontend image tag to v3.4.0
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#1201 feat(security-apps): Update stackrox from 4.2.2 to 4.3.4
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#1202 feat(infra-apps): Update cert-manager from 1.13.2 to 1.14.3
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1203 feat(infra-apps): Update rbac-manager from 1.15.1 to 1.19.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1204 feat(openshift-etcd-backup): add s3 support
  README.md
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
  charts/openshift-etcd-backup/templates/cronjob.yaml
  charts/openshift-etcd-backup/templates/pvc.yaml
  charts/openshift-etcd-backup/templates/secret.yaml
  charts/openshift-etcd-backup/values.yaml
Labels: size/M

#1206 chore(etcd-backup): bump to 1.8.1
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
  charts/openshift-etcd-backup/templates/secret.yaml
Labels: size/XS
