Repository adfinis/helm-charts, pull requests merged in 2024-11, with the labels that each got.

#1334 feat(infra-apps): Upgrade Argo CD from 2.12.4 to 2.13.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1335 ci(pre-commit): only include the chart once
  .pre-commit-config.yaml
Labels: size/XS

#1336 chore(openshift-etcd-backup): update image to v1.8.13
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1337 feat(infra-apps): Update Argo CD from 2.13.0 to 2.13.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1339 feat(misc-apps): Update argo-apps chart from 2.0.0 to 2.0.2
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/L

#1338 fix(keycloak-operator): Update from 26.0.1 to 26.0.6
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1342 chore: update stackrox from 4.4.3 to 4.5.5
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/M
