Repository adfinis/helm-charts, pull requests merged in 2024-01, with the labels that each got.

#1172 fix(argoconfig): Remove empty syncPolicy from application template
  charts/argoconfig/Chart.yaml
  charts/argoconfig/README.md
  charts/argoconfig/templates/_application.yaml
Labels: size/XS

#1173 fix(*-apps): Update argoconfig dependency
  charts/argo-apps/Chart.lock
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/azure-apps/Chart.lock
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/backup-apps/Chart.lock
  charts/backup-apps/Chart.yaml
  charts/backup-apps/README.md
  charts/infra-apps/Chart.lock
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/logging-apps/Chart.lock
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/misc-apps/Chart.lock
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/security-apps/Chart.lock
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/storage-apps/Chart.lock
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/tracing-apps/Chart.lock
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
Labels: size/L

#1175 feat(infra-apps): Update Argo CD from 2.9.3 to 2.9.4
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1176 chore: Update helm from v3.10.3 to v3.14.0
  .env
  .github/workflows/release.yaml
  .github/workflows/test.yaml
Labels: size/XS

#1179 chore: Update helm-docs from v1.11.0 to v1.12.0
  .env
  .pre-commit-config.yaml
  hack/config/helm-docs/README.md.gotmpl
Labels: size/XS

#1185 feat(argo-apps): Update Argo Rollouts from 1.6.0 to 1.6.4
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/M

#1188 feat(misc-apps): Update OpenCost from 1.105.2 to 1.108.0
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/M

#1178 chore: update gomplate from 3.9.0 to 3.11.7
  .env
Labels: size/XS

#1180 chore: Udpate yq from 4.9.6 to 4.40.5
  .env
Labels: size/XS

#1182 chore: Update all build-time CRDs
  .env
Labels: size/S

#1192 chore(ci): fix preinstalled CRDs
  .env
  hack/deploy/init.sh
Labels: size/XS

#1190 feat(security-apps): Update Kyverno from v1.10.0 to v1.11.4
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/M

#1187 feat(infra-apps): Update ingress-nginx from 1.9.4 to 1.9.5
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1191 feat(misc-apps): Update downscaler chart from 0.7.3 to 0.7.4
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/M

#1181 chore: Update ArtifactHub cli from v1.10.0 to v1.17.0
  .env
Labels: size/XS

#1164 feat(tracing-apps): Update jaeger-operator chart from 2.43.0 to 2.50.1
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/S

#1194 chore(timed): update frontend image tag to v3.3.0
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S
