Repository adfinis/helm-charts, pull requests merged in 2024-10, with the labels that each got.

#1324 chore(kubernetes-etcd-backup): bump appVersion to 1.2.1
  charts/kubernetes-etcd-backup/Chart.yaml
  charts/kubernetes-etcd-backup/README.md
Labels: size/S

#1325 chore(openshift-etcd-backup): update image to v1.8.12
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1326 feat(infra-apps): Update cert-manager from 1.15.1 to 1.16.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1327 feat(keycloak-operator): Update to 26.0.0
  README.md
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1329 Fix typo in argocd-app-of-apps.md
  docs/argocd-app-of-apps.md
Labels: size/XS

#1328 fix(infra-apps): Update cert-manager from 1.16.0 to 1.16.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1330 fix(keycloak-operator): Update from 26.0.0 to 26.0.1
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M
