Repository adfinis/helm-charts, pull requests merged in 2024-05, with the labels that each got.

#1221 fix(infra-apps): Update Argo CD from 2.10.4 to 2.10.9
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1222 chore(openshift-etcd-backup): update openshift-etcd-backup to 1.8.6
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1223 chore(timed): update frontend to v3.6.0
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/values.yaml
Labels: size/S

#1224 chore(timed): mark chart as deprecated
  README.md
  charts/timed/Chart.yaml
  charts/timed/README.md
Labels: size/S

#1225 feat(infra-apps): Update Argo CD from 2.10.9 to 2.11.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1228 feat(infra-apps): Update nginx-ingress chart from 4.9.0 to 4.10.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1229 feat(infra-apps): Deprecate kube-event-exporter
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1231 feat(infra-apps): Update kube-prometheus-stack from 54.2.2 to 58.6.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1230 feat(misc-apps): Update argocd-apps from 1.4.1 to 2.0.0
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/M

#1232 feat(infra-apps): Update Argo CD from 2.11.0 to 2.11.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1235 feat(infra-apps): Update Velero from 1.12.2 to 1.13.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1234 feat(logging-apps): Update Loki from 2.9.3 to 3.0
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/M

#1226 feat(keycloak-operator): Update keycloak-operator and keycloak from 23.0.3 to 24.0.4
  README.md
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1205 chore(ci): Update helm-docs from 1.12.0 to 1.13.0
  .env
Labels: size/XS

#1259 feat(argo-apps): Update argo-rollouts from 1.6.4 to 1.6.6
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/M

#1257 chore(azure-apps): Bump azureKvCsiProvider to v1.5.4
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/S

#1260 chore(misc-apps): update metallb to 0.14.5
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/M

#1256 chore(mimir): update to 5.3.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M
