Repository adfinis/helm-charts, pull requests merged in 2024-06, with the labels that each got.

#1262 chore(storage-apps): bump csi-driver-smb from 1.9.* to 1.14.0
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/values.yaml
Labels: size/S

#1263 feat(infra-apps): Update Argo CD from 2.11.1 to 2.11.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1266 feat(infra-apps): update cert manager 1.15.0
  .env
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1267 chore(openshift-etcd-backup): update image to v1.8.8
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1265 feat(security-apps): update dex chart to 0.18.0
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#1271 chore(kps): update to 60.0.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1272 [issue 1270] Feature: disable operator templates generation
  README.md
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/ci/default-values.yaml
  charts/keycloak-operator/ci/operand-values.yaml
  charts/keycloak-operator/templates/NOTES.txt
  charts/keycloak-operator/templates/operator/clusterrole.yaml
  charts/keycloak-operator/templates/operator/deployment.yaml
  charts/keycloak-operator/templates/operator/rolebinding.yaml
  charts/keycloak-operator/templates/operator/roles.yaml
  charts/keycloak-operator/templates/operator/service.yaml
  charts/keycloak-operator/templates/operator/serviceaccount.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1275 chore(openshift-etcd-backup): update image to v1.8.9
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1277 fix: change from operator. to kc.operator. keys
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/templates/operator/deployment.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1264 feat(tracing-apps): Update otel-collector from 0.82.0 to 0.101.0
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/L

#1276 feat(keycloak-operator): Update Keycloak to 25.0.0 and update CRDs to match
  README.md
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/ci/operand-values.yaml
  charts/keycloak-operator/crds/keycloakrealmimports.k8s.keycloak.org-v1.yml
  charts/keycloak-operator/crds/keycloaks.k8s.keycloak.org-v1.yml
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/templates/keycloak/keycloakrealmimport.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
  charts/keycloak-operator/values.yaml
Labels: size/XXL

#1284 chore(tracing-apps): update chart versions
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
  charts/tracing-apps/values.yaml
Labels: size/L

#1283 chore(security-apps): update chart versions
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/L

#1282 chore(misc-apps): update chart version
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/L

#1280 chore(azure-apps): update charts
  charts/azure-apps/Chart.yaml
  charts/azure-apps/README.md
  charts/azure-apps/values.yaml
Labels: size/M

#1278 chore(infra-apps): update charts
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1279 chore(argo-apps): update argo-rollouts
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/M

#1281 chore(logging-apps): update helm-charts
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/M
