Repository adfinis/helm-charts, pull requests merged in 2025-09, with the labels that each got.

#1496 chore(security-apps): Mark falco as deprecated
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
Labels: size/XS

#1500 chore(mimir): update to 5.8.0 chart
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1506 chore(security-apps): bumping kyvernoPolicies chart version
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#1513 chore(security-apps): Bumping dex chart to 0.24.0
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#1518 fix(tracing-apps): Mark otel collector update a breaking change
  README.md
  charts/tracing-apps/Chart.yaml
  charts/tracing-apps/README.md
Labels: size/S

#1490 chore(logging-apps): Bump loki from 6.32.0 to 6.38.0
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/values.yaml
Labels: size/M

#1497 chore(security-apps): Update vaultMonitoring from 0.4.2 to 0.6.0
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S
