Repository adfinis/helm-charts, pull requests merged in 2025-04, with the labels that each got.

#1381 chore(hedgdoc): Bump hedgdoc from 1.10.0 to 1.10.2
  charts/hedgedoc/Chart.yaml
  charts/hedgedoc/README.md
Labels: size/S

#1382 feat(security-apps): update Kyverno from 1.12.4 to 1.13.4
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/M

#1383 fix(security-apps): downgrade kyverno chart to 3.3.7
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/S

#1384 feat(infra-apps): update Argo CD from 2.13.1 to 2.14.8
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1385 fix: upgrade openshift-etcd-backup image to v1.9.3
  charts/openshift-etcd-backup/Chart.yaml
  charts/openshift-etcd-backup/README.md
Labels: size/S

#1387 feat(infra-apps): update cert-manager from 1.16.2 to 1.17.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1388 chore(Kube-Prometheus-Stack): update to 67.11.0 - First release with Prometheus v3
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1392 feat(keycloak-operator): Update Keycloak from 26.0.7 to 26.2.1
  README.md
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1394 fix(keycloak-operator): update CRDs for Keycloak 26
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/ci/operand-values.yaml
  charts/keycloak-operator/crds/keycloakrealmimports.k8s.keycloak.org-v1.yml
  charts/keycloak-operator/crds/keycloaks.k8s.keycloak.org-v1.yml
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/templates/keycloak/keycloakrealmimport.yaml
  charts/keycloak-operator/templates/operator/clusterrole.yaml
  charts/keycloak-operator/templates/operator/deployment.yaml
  charts/keycloak-operator/templates/operator/roles.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/XXL

#1395 fix(keycloak-operator): update keycloak from 26.2.1 to 26.2.2
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M
