Repository adfinis/helm-charts, pull requests merged in 2025-01, with the labels that each got.

#1341 feat(kubernetes-etcd-backup): s3 support for kubernetes etcd backups
  README.md
  charts/kubernetes-etcd-backup/Chart.yaml
  charts/kubernetes-etcd-backup/README.md
  charts/kubernetes-etcd-backup/templates/configmap.yaml
  charts/kubernetes-etcd-backup/templates/cronjob.yaml
  charts/kubernetes-etcd-backup/templates/secret.yaml
  charts/kubernetes-etcd-backup/values.yaml
Labels: size/M

#1360 feat: Add a HelmChartRepository for use with OpenShift
  README.md
  adfinis-charts-repo.yaml
  hack/ci/github/steps/update-page.sh
  hack/config/update-readme/README.md.gotmpl
Labels: size/S

#1359 chore(storage-apps): Bump minio due to CVE-2024-55949
  charts/storage-apps/Chart.yaml
  charts/storage-apps/README.md
  charts/storage-apps/values.yaml
Labels: size/M

#1361 feat(cert-manager-monitoring): introduce critical severity for CertManagerCertExpirySoon alert
  charts/cert-manager-monitoring/Chart.yaml
  charts/cert-manager-monitoring/README.md
  charts/cert-manager-monitoring/templates/prometheus/prometheusrule.yaml
Labels: size/S

#1363 chore(timed): Remove deprecated chart
  charts/timed/.helmignore
  charts/timed/Chart.lock
  charts/timed/Chart.yaml
  charts/timed/README.md
  charts/timed/ci/default-values.yaml
  charts/timed/files/workreport.ots
  charts/timed/grafana/dashboards/timed.json
  charts/timed/templates/NOTES.txt
  charts/timed/templates/_helpers.tpl
  charts/timed/templates/certificate-psql.yaml
  charts/timed/templates/configmap-backend.yaml
  charts/timed/templates/configmap-frontend.yaml
  charts/timed/templates/configmap-workreport.yaml
  charts/timed/templates/cronjob-backend.yaml
  charts/timed/templates/deployment-backend.yaml
  charts/timed/templates/deployment-frontend.yaml
  charts/timed/templates/grafana/configmap-dashboard.yaml
  charts/timed/templates/ingress.yaml
  charts/timed/templates/job-dbmigrate.yaml
  charts/timed/templates/prometheus/podmonitor.yaml
  charts/timed/templates/secret-backend.yaml
  charts/timed/templates/service-backend.yaml
  charts/timed/templates/service-frontend.yaml
  charts/timed/templates/service-postgresql.yaml
  charts/timed/templates/tests/test-connection.yaml
  charts/timed/values.yaml
Labels: size/XXL

#1364 chore(argo-apps): Remove deprecated argocd-notifications component
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/templates/argocd-notifications.yaml
  charts/argo-apps/values.yaml
Labels: size/M

#1365 chore(infra-apps): Add fail for kube-event-exporter deprecation
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/ci/default-values.yaml
  charts/infra-apps/templates/kubernetes-event-exporter.yaml
Labels: size/M

#1366 chore(security-apps): Fail deprecated gangway installations
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/ci/default-values.yaml
  charts/security-apps/templates/gangway.yaml
Labels: size/M

#1367 chore(logging-apps): Fail deprecated loki-stack installations
  charts/logging-apps/Chart.yaml
  charts/logging-apps/README.md
  charts/logging-apps/templates/loki-stack.yaml
Labels: size/M

#1371 feat(etcd-backup): podAnnotations
  README.md
  charts/kubernetes-etcd-backup/Chart.yaml
  charts/kubernetes-etcd-backup/README.md
  charts/kubernetes-etcd-backup/templates/cronjob.yaml
  charts/kubernetes-etcd-backup/values.yaml
Labels: size/S
