Repository adfinis/helm-charts, pull requests merged in 2025-08, with the labels that each got.

#1478 feat(infra-apps): Update cert-manager from 1.18.1 to 1.18.2
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1480 feat(infra-apps): Update cert-manager-monitoring from 0.1.* to 0.2.0
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/S

#1486 chore: Update kube-prom-stack from 75.3.0 to 76.4.1
  charts/infra-apps/Chart.yaml
  charts/infra-apps/README.md
  charts/infra-apps/values.yaml
Labels: size/M

#1482 chore: upgrade argoRollouts chart version from 2.40.2 to 2.40.3
  charts/argo-apps/Chart.yaml
  charts/argo-apps/README.md
  charts/argo-apps/values.yaml
Labels: size/S

#1477 fix(keycloak-operator): allow configuring keycloak.ingress.annotations
  charts/keycloak-operator/Chart.yaml
  charts/keycloak-operator/README.md
  charts/keycloak-operator/ci/operand-values.yaml
  charts/keycloak-operator/templates/keycloak/keycloak.yaml
  charts/keycloak-operator/tests/__snapshot__/default_test.yaml.snap
  charts/keycloak-operator/tests/__snapshot__/operand_test.yaml.snap
Labels: size/M

#1491 chore(secretsStoreCsiDriver): Bump to 1.5.3
  charts/security-apps/Chart.yaml
  charts/security-apps/README.md
  charts/security-apps/values.yaml
Labels: size/L

#1479 feat(misc-apps): Update ChartMuseum from 0.16.1 to 0.16.3
  charts/misc-apps/Chart.yaml
  charts/misc-apps/README.md
  charts/misc-apps/values.yaml
Labels: size/M
